### PR TITLE
Add initial vue setup for the front end

### PR DESCRIPTION
**Pull request by veredrec**
Relates #2

- Initiate `Node`
- Install `vue-cli`
- Render `Hello World`

### CODE REVIEW

**Review by AryanJ-NYC — COMMENTED** [review]
Just want to point out that after the back-end is merged, we should rename `bears-3` to `frontend`. We can merge now with it named as `bears-3` or we can take care of it in this PR.

@veredrec, what do you think? Do you want to save this task for later or do it now?

**Review by ElleeB — APPROVED** [review]

**Comment by veredrec** [comment]
@AryanJ-NYC if it's fine with you, I prefer to leave it like that for now, but you are definitely right that we should change the name in the next PR that is related to the frontend. Also, we will make some changes in the json file, which I left as default.

**Comment by veredrec** [comment]
After thinking about it again - why not changing it now?... So I changed the folder name to `frontend` and made some minor changes in the `package.json` file. @AryanJ-NYC is this what you meant? If so, one of us can merge it. Thanks!

**Review by AryanJ-NYC — APPROVED** [review]
Nice job!

Keep in mind that root `package.json` will present merge conflicts for @ElleeB's PR.

**Comment by veredrec** [comment]
Yes, that's right... should we do anything about it now before merging?

**Pull request merged**
